name: Master

on:
  push:
    branches:
      - master
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 6 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v1
      -name: Running
      run: | # python
          echo "Running!"
