name: Master

on:
  push:
    branches:
      - master
  schedule:
    - cron: "7 6 * * *"  # Runs daily at 6:05 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  # ✅ Correct 'uses' step
      - name: Running               # ✅ Correct 'run' step
        run: |
          echo "Running!"
