name: Super-Linter

on: 
  push:
    branches:
      - master
  schedule:
    - cron: "35 11 * * *"  
  workflow_dispatch:

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: 23f3004293@ds.study.iitm.ac.in  # ✅ MUST appear exactly like this
        run: echo "This step is named after my email"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
           persist-credentials: true

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes if any
        run: |
            git commit -m "chore: update after lint"

