name: Super-Linter

on: 
  push:
    branches:
      - master
  schedule:
    - cron: "26 11 * * *"  # 6:10 AM IST
  workflow_dispatch:

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: 23f3004293@ds.study.iitm.ac.in  # ✅ MUST appear exactly like this
        run: echo "This step is named after my email"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
           persist-credentials: true

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes if any
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: update after lint"
            git push origin master
          else
            echo "No changes to commit"
          fi

