name: Master

on:
  push:
    branches:
      - master
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "5 6 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Running
        run: |
          echo "Running!"

