name: Super-Linter

on: 
  push:
    branches:
      - master
  schedule:
    - cron: "17 6 * * *"  # 6:10 AM IST
  workflow_dispatch:

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: 23f3004293@ds.study.iitm.ac.in  # ✅ MUST appear exactly like this
        run: echo "This step is named after my email"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

