name: Daily Auto Commit

on:
  schedule:
    - cron: '18 15 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp by 23f3004293@ds.study.iitm.ac.in
        run: |
          echo "Last updated at: $(date -u)" > last_updated.txt

      - name: Commit and Push
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.json
          git commit -m "Update IMDb Top 250 data [skip ci]" || exit 0
          git push
